name: xikipedia_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  brotli: ^0.6.0
  cached_network_image: ^3.3.1
  flutter_cache_manager: ^3.3.1
  pool: ^1.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/smoldata.json.br